version: '3.8'

services:
  inji-verify:
    image: mosipid/inji-verify:0.8.0
    ports:
      - "5000:80"
    environment:
      - INTERNET_CONNECTIVITY_CHECK_ENDPOINT=${INTERNET_CONNECTIVITY_CHECK_ENDPOINT-https://dns.google/}
      - INTERNET_CONNECTIVITY_CHECK_TIMEOUT=${INTERNET_CONNECTIVITY_CHECK_TIMEOUT-10000}